version: '3'
services:
  app:
    container_name: 'node_mongo_app'
    restart: always
    build: .
    ports: 
      - "8080:8000"
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - "27017:27017"
       
